export enum ImportStatementStateEnum {
  WaitingForStatement = "WAITING_FOR_STATEMENT",
  PRE_PROCESSING_STATEMENT = "PRE_PROCESSING_STATEMENT",
  PREVIEW_READY_AWAITING_CONFIRMATION = "PREVIEW_READY_AWAITING_CONFIRMATION",
  ProcessingStatement = "PROCESSING_STATEMENT",
  ReviewExpensesFound = "REVIEW_EXPENSES_FOUND",
  StatementProcessed = "STATEMENT_PROCESSED",
}
